// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_3_world_achievement = "CgkIlojH6M0cEAIQAQ"; // <GPGSID>
        public const string leaderboard_stage_perfection = "CgkIlojH6M0cEAIQCA"; // <GPGSID>
        public const string leaderboard_world_perfection = "CgkIlojH6M0cEAIQCQ"; // <GPGSID>
        public const string achievement_robot_rock_unlocked = "CgkIlojH6M0cEAIQBA"; // <GPGSID>
        public const string leaderboard_best_world_score = "CgkIlojH6M0cEAIQBw"; // <GPGSID>
        public const string achievement_5_worlds_achievement = "CgkIlojH6M0cEAIQAg"; // <GPGSID>
        public const string achievement_technologic_unlocked = "CgkIlojH6M0cEAIQBQ"; // <GPGSID>
        public const string achievement_10_worlds_achievement = "CgkIlojH6M0cEAIQAw"; // <GPGSID>
        public const string leaderboard_best_stage_score = "CgkIlojH6M0cEAIQBg"; // <GPGSID>

}

